# Generated by Django 4.0.dev20210219192511 on 2021-03-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='sub_category',
        ),
    ]
