# Generated by Django 4.0.dev20210219192511 on 2021-03-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_cat_name_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
    ]
