# Generated by Django 4.0.dev20210219192511 on 2021-03-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='items.category'),
        ),
    ]
