# Generated by Django 4.0.dev20210219192511 on 2021-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_rename_item_cartproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
