# Generated by Django 4.0.dev20210219192511 on 2021-03-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
    ]
