# Generated by Django 4.0.dev20210219192511 on 2021-03-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210311_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
